# Manual triggers only for now, until we add more logic on when to build, test, and deploy
trigger: none
pr: none

pool:
  vmImage: "macOS-latest"

variables:
  scheme: ""
  sdk: iphoneos
  configuration: Release
  rubyVersion: "3.1.x" # Define the Ruby version here
  System.Debug: false

jobs:
  - job: BuildAndDeploy
    displayName: Install Dependencies, Build and Deploy to TestFlight
    variables:
      - group: transit-variables
    steps:
      - task: Cache@2
        inputs:
          key: 'gems | "$(Agent.OS)" | react-native-app/Gemfile.lock'
          path: $(System.DefaultWorkingDirectory)/react-native-app/vendor/bundle
          restoreKeys: gems | "$(Agent.OS)"
      - task: UseRubyVersion@0
        inputs:
          versionSpec: $(rubyVersion)
          addToPath: true
      - script: |
          cd react-native-app
          gem install bundler cocoapods
          bundle install --path vendor/bundle
        displayName: Install Bundler, Cocoapods, and Ruby dependencies

      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | react-native-app/package-lock.json'
          path: $(System.DefaultWorkingDirectory)/react-native-app/node_modules
          restoreKeys: npm | "$(Agent.OS)"
      - script: |
          cd react-native-app
          npm ci
        displayName: Install NPM dependencies

      - task: Cache@2
        inputs:
          key: 'pods | "$(Agent.OS)" | react-native-app/ios/Podfile.lock'
          path: $(System.DefaultWorkingDirectory)/react-native-app/ios/Pods
          restoreKeys: pods | "$(Agent.OS)"
      - script: |
          cd react-native-app/ios
          pod install
        displayName: Install Pod dependencies

      - script: |
          cd react-native-app
          bundle exec fastlane ios beta
        displayName: Build and Deploy to TestFlight
        env:
          APP_STORE_CONNECT_ISSUER_ID: "69a6de84-80a4-47e3-e053-5b8c7c11a4d1"
          APP_STORE_CONNECT_KEY_CONTENT: $(APP_STORE_CONNECT_KEY_CONTENT)
          APP_STORE_CONNECT_KEY_ID: "TB5LMSYCHW"
          MATCH_PASSWORD: $(MATCH_PASSWORD)
          MATCH_CERTIFICATES_REPO_URL: https://$(CERTIFICATES_REPO_READ_ACCESS_TOKEN)@github.com/transit-astrology/transit-certificates.git
          SB_ANON_KEY: $(SB_ANON_KEY)
          APP_ENV: prod
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
