create table "public"."Astrological Details " (
    "astrological_details_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid,
    "sign_name" text not null,
    "sign" text not null,
    "hours" smallint not null,
    "minutes" smallint not null
);


alter table "public"."Astrological Details " enable row level security;

alter table "public"."Conversations" alter column "created_at" set not null;

alter table "public"."Messages" alter column "role" set not null;

alter table "public"."User Details" add column "birth_latitude" double precision;

alter table "public"."User Details" add column "birth_longitude" double precision;

alter table "public"."User Details" alter column "birth_location" set data type text using "birth_location"::text;

alter table "public"."User Details" alter column "created_at" set not null;

CREATE UNIQUE INDEX "Astrological Details _pkey" ON public."Astrological Details " USING btree (astrological_details_id);

alter table "public"."Astrological Details " add constraint "Astrological Details _pkey" PRIMARY KEY using index "Astrological Details _pkey";

alter table "public"."Astrological Details " add constraint "Astrological Details _user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."Astrological Details " validate constraint "Astrological Details _user_id_fkey";

alter table "public"."Conversations" add constraint "Conversations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."Conversations" validate constraint "Conversations_user_id_fkey";

alter table "public"."Messages" add constraint "Messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES "Conversations"(conversation_id) ON DELETE SET NULL not valid;

alter table "public"."Messages" validate constraint "Messages_conversation_id_fkey";

alter table "public"."Messages" add constraint "Messages_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."Messages" validate constraint "Messages_user_id_fkey";


