create table "public"."Conversations" (
    "conversation_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" text
);


alter table "public"."Conversations" enable row level security;

create table "public"."Messages" (
    "message_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "conversation_id" bigint,
    "role" text,
    "content" text
);


alter table "public"."Messages" enable row level security;

CREATE UNIQUE INDEX "Conversations_conversation_id_key" ON public."Conversations" USING btree (conversation_id);

CREATE UNIQUE INDEX "Conversations_pkey" ON public."Conversations" USING btree (conversation_id);

CREATE UNIQUE INDEX "Messages_message_id_key" ON public."Messages" USING btree (message_id);

CREATE UNIQUE INDEX "Messages_pkey" ON public."Messages" USING btree (message_id);

alter table "public"."Conversations" add constraint "Conversations_pkey" PRIMARY KEY using index "Conversations_pkey";

alter table "public"."Messages" add constraint "Messages_pkey" PRIMARY KEY using index "Messages_pkey";

alter table "public"."Conversations" add constraint "Conversations_conversation_id_key" UNIQUE using index "Conversations_conversation_id_key";

alter table "public"."Messages" add constraint "Messages_message_id_key" UNIQUE using index "Messages_message_id_key";


