drop policy "Enable insert for authenticated users only" on "public"."Astrological Details";

drop policy "Enable read for authenticated users based on user_id" on "public"."Astrological Details";

drop policy "Enable update for users based on user_id" on "public"."Astrological Details";

alter table "public"."Astrological Details" drop constraint "Astrological Details_user_id_fkey";

alter table "public"."Astrological Details" drop constraint "Astrological Details _pkey";

drop index if exists "public"."Astrological Details _pkey";

drop table "public"."Astrological Details";

create table "public"."Astrological Details Report" (
    "report_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "astrological_report" jsonb
);


alter table "public"."Astrological Details Report" enable row level security;

create table "public"."User Astrological Details Report" (
    "astrological_details_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid,
    "astrological_report" jsonb
);


alter table "public"."User Astrological Details Report" enable row level security;

CREATE UNIQUE INDEX "Astrological Details Report_pkey" ON public."Astrological Details Report" USING btree (report_id);

CREATE UNIQUE INDEX "Astrological Details _pkey" ON public."User Astrological Details Report" USING btree (astrological_details_id);

alter table "public"."Astrological Details Report" add constraint "Astrological Details Report_pkey" PRIMARY KEY using index "Astrological Details Report_pkey";

alter table "public"."User Astrological Details Report" add constraint "Astrological Details _pkey" PRIMARY KEY using index "Astrological Details _pkey";

alter table "public"."User Astrological Details Report" add constraint "User Astrological Details Report_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."User Astrological Details Report" validate constraint "User Astrological Details Report_user_id_fkey";

create policy "Enable insert for authenticated users only"
on "public"."User Astrological Details Report"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read for authenticated users based on user_id"
on "public"."User Astrological Details Report"
as permissive
for select
to authenticated
using ((auth.uid() = user_id));


create policy "Enable update for users based on user_id"
on "public"."User Astrological Details Report"
as permissive
for update
to authenticated
using ((auth.uid() = user_id))
with check (true);



