# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
  end

  desc "Build and upload to TestFlight"
  lane :beta do
  
    #credentials passed into match and the pilot command automatically
    api_key = app_store_connect_api_key( 
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )
   
    match # Fetch apple certificates and provisioning profiles (config in MatchFile)
    
    latest_build_number = app_store_build_number(
      live: false,
      api_key: api_key,
      app_identifier: "com.transitastrology-"
    )

    puts "Latest build number: #{latest_build_number}"
   
    # increment build number before gym to avoid duplicate build number error
    increment_build_number(
      build_number: (latest_build_number.to_i + 1).to_s,
      xcodeproj: "./ios/ReactNativeApp.xcodeproj"
    )

    # Build ios app
    gym( 
      scheme: "ReactNativeApp",
      workspace: "./ios/ReactNativeApp.xcworkspace",
      silent: true
    )
    
    # Upload to TestFlight
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match # Fetch apple certificates and provisioning profiles (config in MatchFile)
    gym(scheme: "ReactNativeApp", workspace: "./ios/ReactNativeApp.xcworkspace") # Build the app
    deliver(force: true) # Upload to the App Store
  end
end